### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by eclisia** [pawelsikora/mkdocs-with-confluence#9]
Dear @pawelsikora 
First : thanks for your plugin.
I'm trying to use it with Gitlab CI/CD.

**I've got some questions (some basic usage).**
But, before, let me present my configuration

## Current configuration I used (and led to my issue)
* CI/CD : Gitlab
* docker image use : image python:3.8-buster

## Issue
When running, I've got the following pipeline error message 
```
ModuleNotFoundError: No module named 'requests'
```

## Complementary informations:
I've put my configuration for the plugin into the ``mkdocs.yml``
* **Is is the good place to put the configuration ?**
* Why the "import requests" from the python plugin is not working ? Is it necessary for me to update my docker image with this dependancy ?
* For password with special character : should I put it with some mask ? (refer : https://docs.gitlab.com/ee/ci/variables/index.html#mask-a-cicd-variable) or with quote  ?

```yml
plugins:
  - search:
      lang:
        - fr
        - en
  - macros
  - mkdocs-confluence: #For conversion of mkdocs into confluence
      host_url: https://my_confluence.fr/rest/api/content?type=page&spaceKey=bac&expand=ancestros&limit=100
      space: bac
      parent_page_name: Test_Florent
      username: myuser_name
      password: "MYPASSWORD!*ù$^4_with_special_character"
      verbose: true
      dryrun: true

```

AND LOT : thanks for your support.
